### ISSUE TITLE
Change colour

### ISSUE THREAD

**Issue by rimapaul** [ElleHacks/elleHacks.github.io#53]
Change the dominant colour from last year - blue, to our dominant colour for this year - green (#49AB8B). You can find our main colours in the colour slack channel

**Comment by LauraTatianaToro** [comment]
Suggestion: Use SASS to create color variables in seperate .scss file

**Comment by rimapaul** [comment]
> Suggestion: Use SASS to create color variables in seperate .scss file

This is a great idea! Currently, we have CSS files, but it would bee great to have scss files. If you would like you can take the charge in that, I have created an issues for it.
